// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBfdWE59Drcz7zh_QdH3_M_mI5ejtSn7u8',
//     appId: '1:109985204482:android:f3de83c5cdcb93c1b79a1b',
//     messagingSenderId: '109985204482',
//     projectId: 'closet-ai-8c1fc',
//     storageBucket: 'closet-ai-8c1fc.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD_ROczkAJlbP2_CXHLVkxUv9zSn4uzCLs',
//     appId: '1:109985204482:ios:481b6f6335b4c1f5b79a1b',
//     messagingSenderId: '109985204482',
//     projectId: 'closet-ai-8c1fc',
//     storageBucket: 'closet-ai-8c1fc.appspot.com',
//     androidClientId: '109985204482-30l4ct0fq2bbp0cube5k8cdsa0f2bked.apps.googleusercontent.com',
//     iosClientId: '109985204482-a0s3r87fp57n3lf4mjk3ehv5dks6vrhk.apps.googleusercontent.com',
//     iosBundleId: 'com.closet.ai',
//   );
// }
